version: '3'
services:
  flask-app:
    build: .
    container_name: flask-con
    ports:
      - "4000:80"
    networks:
      - my-network
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    logging:
      driver: gcplogs
      options:
        max-size: 10m
        max-file: "3"
  redis:
    image: redis
    container_name: redis-con
    networks:
      - my-network

networks:
  my-network:
